### ISSUE TITLE
Request to add % played of a .stm file

### ISSUE THREAD

**Issue by kinv** [faush01/plugin.video.embycon#47] opened 2019-01-01 19:05 UTC
Hi,

Wondering if would be possible to add support for play % of strm files. Works with normal files and with .strm files with other amby apps.

To clarify I mean tracking that I stopped a movie at 50%, right now if I play a file for more than 1% it just marks as watched.

Hope this is possible as I really like using embycon.

Thanks.

**Comment by faush01** [comment] 2019-01-01 20:51
This is actually not an EmbyCon limitation, it is a limitation of the Emby Server.

The problem is that the Emby server does not know the runtime duration of the STRM file thus it can not set a percentage done as the total duration is zero.

To check this have a look at the STRM items in Emby and they will not have runtimes. 

I think there have been improvements on this a while back that Emby would try to scan the contents of the STRM file and work out the runtime duration of the item and set that info in the DB. One problem with this approach is that if only the client knows how to play the content of the STRM file then the Emby server will never be able to get the runtime. This is the case for STRM files that have links to Kodi plugins in them like the netflix one.

There are also plans to allow a client to update the Emby server with what the client thinks the runtime of an item in as it is playing thus allows runtimes and progress for STRM files once they start playback.

**Comment by kinv** [comment] 2019-01-01 21:00
Thanks for the reply.

My .strm files are mounted in emby. In the web app it tracks as well as samsung tv and android and emby for kodi (only ones I have tested). I don't pretend to know anything about it, Just thought I would see if it was something that was possible :) 

Anyway its a great plugin, I appreciate the time you have taken to develop this. 👍

**Comment by faush01** [comment] 2019-01-01 22:17
If you are saying that all other clients can in fact track progress but EmbyCin can not then yes that might be an EmbyCon add-on issue. I this case a debug log will help track down the issue.

**Comment by kinv** [comment] 2019-01-01 22:19
Indeed. Anything in particular you want me to do? just play a .strm file skip it to about halfway, stop it then send you the debug log?

**Comment by faush01** [comment] 2019-01-02 01:17
Find an STRM item that has a runtime and can be correctly tracked for progress in other clients.
Turn on Kodi Debugging and restart Kodi
Play the file using EmbyCon, skip to the mid poin in the movie and let it play for 30 sec or so then sto pit
Send me the Kodi log, PM on the forum is best.

**Comment by kinv** [comment] 2019-01-02 13:02
Hi, I have sent you a PM with the log file.

**Comment by ddurdle** [comment] 2019-01-02 21:32
It isn't really a limitation of emby server.  Emby server is indexing the runtime for a .strm file based on what it mapped to.  In all fairness, Emby on KODI plugin supports resume points and % watched for STRM files.

**Comment by faush01** [comment] 2019-01-02 21:54
Yes correct, if the emby server can determine the runtime of the STRM and the file that it links to then all clients should be able to set the progress.
There are some files like links to kodi plugin links that the emby server will not be able to detemin and there are plans to help with that by allowing the client to report the runtime to the server to update it.
I have a log nwo and will look onto why EmbyCon is not tracking the progress of the above issue now.

**Comment by faush01** [comment] 2019-01-05 20:45
Latest beta has a fix for this.

**Closed by faush01** 2019-01-05 20:45 UTC
