### ISSUE TITLE
Connection error the read operation timed out

### ISSUE THREAD

**Issue by prydda** [faush01/plugin.video.embycon#93] opened 2020-01-21 18:23 UTC
When I go to the folder Movies I get the old view grid at first, apporx 30sec later I get the the error message "connection error the read operation timed out", is this comming from embycon itself or is the server slow? 

Here is a logfile: 
https://del.dog/lolyghynug

**Comment by faush01** [comment] 2020-01-21 21:27
The first load of data is from the local EmbyCon cache, Kodi is then trying to check if the data loaded has changed and is getting a time out on the response.

One thing you can try to see how oftern it times out is turn off caching data in the EmbyCon advanced settings. This will then show you the error in real time so you can see what pages are causing the time out. 

Time outs are usually network or server related.

**Comment by prydda** [comment] 2020-01-22 22:44
It appears to be when loading the movie section which is rather large; 
https://del.dog/osenecowol.txt

Going back and forth will display the movies again tho. also just noticed, "mark as watched" freezes the screen and takes up to a minute to mark the video.

**Comment by prydda** [comment] 2020-01-22 23:04
Here it's first displayed as wall for fanart, then after approx 30sec it switches to poster (new default view set from embyCon) and then giving me the error read operation timed out, and leaves me with 0 movies, and poster with dots leading me to emby libraries. 

https://del.dog/yphedahuda

**Comment by faush01** [comment] 2020-01-22 23:31
looks like you are having network or Emby Server time out issues.
When using the Emby Web Client do you see any slow downs or time outs?
Turn on "Log timing data" in the EmbyCon addon advanced settings. 
Turn off "Cache server requests"
restart Kodi and try again. then post the log.
This will have extra timing info about the requests begin made in the log.

**Comment by prydda** [comment] 2020-01-23 08:47
emby web is fast, no hickups, slow downs or timeouts. 
Samething happend here as I described above and with embycon debugging + cache off. 
The logfile is almost 200mb https://fil.email/JE0aIKX2

**Comment by faush01** [comment] 2020-01-23 09:10
no, not full debug logging, just timing info:

In the EmbyCon addon advanced settings
Turn on "Log timing data"
Turn off "Cache server requests"

**Comment by prydda** [comment] 2020-01-23 09:22
my bad here is a new one: 
https://del.dog/lisocringe

**Comment by faush01** [comment] 2020-01-23 11:34
Thx.

This shows that for some reason your server is taking a long time to services the request, example:

2020-01-23 10:17:11.599 T:3455255424  NOTICE: EmbyCon.resources.lib.tracking|INFO|timing_data|downloadUrl|1579770958.12|1579771031.6|{server}/emby/Users/{userid}/Items?ParentId=73db5cbba534490885db8ca2622980b2&IsVirtualUnaired=false&IncludeItemTypes=Movie&CollapseBoxSetItems=True&GroupItemsIntoCollections=True&Recursive=true&IsMissing=False&Fields={field_filters}&ImageTypeLimit=1&SortBy=Name&SortOrder=Ascending&format=json

1579770958.12 -> 1579771031.6
73.48 seconds

This just looks like a standard movie list request so I dont know what might be causing your server to be so slow.

I will have a look and see if I can reproduce the issue on my end.

**Comment by faush01** [comment] 2020-01-23 20:22
I can not reproduce this with the default skin.
How are you accessing your movies list?
Switch back the the  default skin and try the following.
access the Movie list from:
Addons->EmbyCon->Global Lists -> Movies -> Movies Show all
Is that still slow.

**Comment by prydda** [comment] 2020-01-27 09:29
I switched to the default skin and it's still slow, It's a really big collection. Maybe that's the issue?

**Comment by faush01** [comment] 2020-01-27 11:44
yeah the bigger the collection the longer it will take. 
you have a few options, use the pages option to view it page by page like in the web client
or use the genres or starts with lists to show just the sub section of the list you are interested in.
unfortunately if it is a huge collection it will take some time to view using this approach.

**Comment by faush01** [comment] 2020-02-01 21:37
I don't think anything can be done in the add-on to fix this so closing this now.

**Closed by faush01** 2020-02-01 21:37 UTC

**Comment by prydda** [comment] 2020-02-07 09:16
when using the page option set to 100 the alphabet list to the right disappears. How can I get the list to show in paged view - that would actually solve-ish the issue with slow init loading.

**Comment by faush01** [comment] 2020-02-07 22:25
this is a skin thing, the add-on does not controller that
